specVersion: 0.2.0
name: hello
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/subquery/subql-starter
schema:
  file: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - kind: substrate/Runtime
    startBlock: 9658000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: BalanceSet
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Deposit
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: DustLost
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Endowed
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Reserved
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: ReserveRepatriated
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Slashed
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Transfer
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Unreserved
        #- handler: handleEvent
        #  kind: substrate/EventHandler
        #  filter:
        #    module: balances
        #    method: Withdraw